branch-defaults:
  ch2-6-end:
    environment: Vue2-master-course-env
  release:
    environment: null
    group_suffix: null
environment-defaults:
  vue3-master-course:
    branch: null
    repository: null
global:
  application_name: vue2-master-course
  branch: null
  default_ec2_keyname: vue2
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
