name: deploy to aws elastic beanstalk
on:
  push:
    branches: 
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate package
        run: ./zip_project.sh

      - name: Generate environment variables
        run: echo "_BUILD_TIME=$(TZ=":Asia/Seoul" date -R|sed 's/.....$//')" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SCRET_ACCESS_KEY }}
          application_name: dante-elastic
          environment_name: Dante-elastic-env
          version_label: ${{ env._BUILD_TIME }}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: beanstalk_vue.zip